theme = "dark_plus"

[editor.file-picker]
hidden = false
git-ignore = false

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":w"
C-a = ":wa"
C-r = ":reload-all"
C-q = ":q"

[keys.insert]
C-s = ":w"
C-a = ":wa"
C-r = ":reload-all"

[editor.soft-wrap]
enable = true
