theme = "dark_plus"

[editor.file-picker]
hidden = false
git-ignore = false

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":w"
C-a = ":wa"
C-r = ":reload-all"
C-q = ":q"
C-y = ":clipboard-yank"
C-v = ":clipboard-paste-after"
C-V = ":clipboard-paste-before"

[keys.insert]
C-s = ":w"
C-a = ":wa"
C-r = ":reload-all"
C-y = ":clipboard-yank"
C-v = ":clipboard-paste-after"
C-V = ":clipboard-paste-before"

[editor.soft-wrap]
enable = true
