#!/bin/bash

open="hx"

pwd="$(eval pwd)"
cwd="cd $pwd"
alias_open="alias open=\"$open\""
hx="$alias_open && clear && hx ."

zellij action new-pane -d right
zellij action move-focus right
zellij action write-chars "$cwd"
zellij action write 13
zellij action write-chars "$hx"
zellij action write 13

zellij action new-pane -d right
zellij action move-focus right
zellij action write-chars "$cwd"
zellij action write 13
zellij action write-chars "lazygit"
zellij action write 13

zellij action move-focus left
zellij action move-focus left

for i in {1..5}
do
	zellij action resize -
done

zellij action new-pane -d down
zellij action move-focus down
zellij action write-chars "$cwd"
zellij action write 13
zellij action write-chars "clear"
zellij action write 13

zellij action move-focus up
zellij action write-chars "yazi"
zellij action write 13
